# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

pod 'hpple', '~> 0.2.0'
pod 'AFNetworking', '~> 2.1.0'
pod 'MagicalRecord', '~> 2.2'
pod 'CocoaLumberjack', '~> 1.8.0'
pod 'SVProgressHUD', '~> 1.0'
pod 'ReactiveCocoa', '~> 2.2.3'
#pod 'libextobjc', '~> 0.3'
#pod 'AFNetworking-ReactiveCocoa', '~> 0.0.2'
pod 'UIAlertView-Blocks', '~> 1.0'

target 'PropertySalesTests' do
  link_with 'PropertySalesTests'
  pod 'OCMock', '~> 2.2.2'
end

link_with 'PropertySales'